#!/usr/bin/env bash

set -e

IMAGE=python
TAG=3.4.6

TARGET=./`basename $1`
LOCAL_DIR=$(dirname `readlink -f $1`)
DOCKER_DIR=/app

if ! docker images | grep -q "^$IMAGE\s\s*$TAG"
then
    >&2 echo == Pulling Docker image
    >&2 docker pull $IMAGE:$TAG
    >&2 echo == Running
fi

docker run --rm -it \
    -v $LOCAL_DIR:$DOCKER_DIR:ro \
    --workdir $DOCKER_DIR \
    $IMAGE:$TAG \
    $TARGET ${@:2}
