#!/usr/bin/env bash

set -e

IMAGE=python:3.4.6

TARGET=`basename $1`
LOCAL_DIR=$(dirname `readlink -f $1`)
DOCKER_DIR=/app

>&2 echo Pulling Docker image

docker pull $IMAGE > /dev/null

>&2 echo Running

docker run --rm -it -v $LOCAL_DIR:$DOCKER_DIR:ro $IMAGE bash -c "$DOCKER_DIR/$TARGET ${@:2}"

>&2 echo Exited without error
